# Generated by Django 5.2.5 on 2025-08-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0002_alter_students_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['name']},
        ),
    ]
