# Generated by Django 5.2.5 on 2025-08-15 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0003_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='brithdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default='male', max_length=6, null=True),
        ),
    ]
