# Generated by Django 5.2.5 on 2025-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0004_students_brithdate_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='level',
            field=models.CharField(blank=True, choices=[('مستوى اول', 'مستوى اول'), ('مستوى ثاني', 'مستوى ثاني'), ('مستوى ثالث', 'مستوى ثالث'), ('مستوى رابع', 'مستوى رابع')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True),
        ),
    ]
