# Generated by Django 5.2.5 on 2025-08-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0005_students_level_alter_students_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.CharField(blank=True, choices=[('موقف قيد', 'موقف قيد'), ('مستجد', 'مستجد'), ('باقي', 'باقي')], default='مستجد', null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='system',
            field=models.CharField(blank=True, choices=[('عام', 'عام'), ('موازي', 'موازي'), ('نفقة خاصة', 'نفقة خاصة'), ('مقاعد مجانية', 'مقاعد مجانية')], default='عام', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='activ',
            field=models.CharField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lab4.guardian'),
        ),
    ]
