# Generated by Django 5.2.5 on 2025-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0006_guardian_students_email_students_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='activ',
            field=models.CharField(default='نشط'),
        ),
    ]
