# Generated by Django 5.2.5 on 2025-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0007_alter_students_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('state', models.CharField(choices=[('نشط', 'نشط'), ('غير نشط', 'غير نشط')], max_length=10, verbose_name='الحالة')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('level', models.CharField(max_length=50, verbose_name='المستوى')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('system', models.CharField(max_length=50, verbose_name='النظام')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
