# Generated by Django 5.2.5 on 2025-08-21 15:22

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0008_students2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('أكاديمي', 'أكاديمي'), ('سلوكي', 'سلوكي'), ('مالي', 'مالي'), ('إداري', 'إداري'), ('الحضور', 'الحضور'), ('الاختبارات', 'الاختبارات')], max_length=50, verbose_name='نوع التقرير')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('content', models.TextField(verbose_name='محتوى التقرير')),
                ('status', models.CharField(choices=[('معلق', 'معلق'), ('قيد المراجعة', 'قيد المراجعة'), ('مكتمل', 'مكتمل'), ('ملغى', 'ملغى'), ('مرفوض', 'مرفوض')], default='معلق', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('منخفض', 'منخفض'), ('متوسط', 'متوسط'), ('عالي', 'عالي'), ('عاجل', 'عاجل')], default='متوسط', max_length=20, verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/attachments/%Y/%m/%d/', validators=[django.core.validators.RegexValidator(message='يسمح فقط بملفات PDF, Word, Excel, الصور, والنصوص', regex='\\.(pdf|doc|docx|xls|xlsx|jpg|jpeg|png|txt)$')], verbose_name='المرفق')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف المرفق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('file_size', models.BigIntegerField(default=0, editable=False, verbose_name='حجم الملف')),
            ],
            options={
                'verbose_name': 'مرفق التقرير',
                'verbose_name_plural': 'مرفقات التقارير',
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='المعلق')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('is_internal', models.BooleanField(default=False, verbose_name='تعليق داخلي')),
            ],
            options={
                'verbose_name': 'تعليق التقرير',
                'verbose_name_plural': 'تعليقات التقارير',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('إنشاء', 'إنشاء'), ('تعديل', 'تعديل'), ('حذف', 'حذف'), ('تغيير الحالة', 'تغيير الحالة'), ('إضافة مرفق', 'إضافة مرفق'), ('إضافة تعليق', 'إضافة تعليق')], max_length=50, verbose_name='الإجراء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('user', models.CharField(max_length=100, verbose_name='المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
            ],
            options={
                'verbose_name': 'سجل التقرير',
                'verbose_name_plural': 'سجلات التقارير',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('template_type', models.CharField(choices=[('أكاديمي', 'أكاديمي'), ('سلوكي', 'سلوكي'), ('مالي', 'مالي'), ('عام', 'عام')], max_length=50, verbose_name='نوع القالب')),
                ('content', models.TextField(verbose_name='محتوى القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قالب التقرير',
                'verbose_name_plural': 'قوالب التقارير',
            },
        ),
        migrations.AlterModelOptions(
            name='students2',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AddField(
            model_name='students2',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AddField(
            model_name='students2',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='students2',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='students2',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='الإيميل'),
        ),
        migrations.AlterField(
            model_name='students2',
            name='level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم'), ('خبير', 'خبير')], max_length=50, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='students2',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. يسمح حتى 15 رقمًا.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='students2',
            name='state',
            field=models.CharField(choices=[('نشط', 'نشط'), ('غير نشط', 'غير نشط')], default='نشط', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='students2',
            name='system',
            field=models.CharField(choices=[('نظامي', 'نظامي'), ('منتسب', 'منتسب'), ('مسائي', 'مسائي')], max_length=50, verbose_name='النظام'),
        ),
        migrations.AddIndex(
            model_name='students2',
            index=models.Index(fields=['email'], name='Lab4_studen_email_6c7ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='students2',
            index=models.Index(fields=['phone'], name='Lab4_studen_phone_38b251_idx'),
        ),
        migrations.AddIndex(
            model_name='students2',
            index=models.Index(fields=['is_active'], name='Lab4_studen_is_acti_432a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='students2',
            index=models.Index(fields=['state'], name='Lab4_studen_state_96859d_idx'),
        ),
        migrations.AddIndex(
            model_name='students2',
            index=models.Index(fields=['level'], name='Lab4_studen_level_8c9b2e_idx'),
        ),
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Lab4.students2', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='reportattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Lab4.report', verbose_name='التقرير'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Lab4.report', verbose_name='التقرير'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Lab4.report', verbose_name='التقرير'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='Lab4_report_status_cb954c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['priority'], name='Lab4_report_priorit_2570d0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='Lab4_report_report__ccb91a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='Lab4_report_created_d02d43_idx'),
        ),
    ]
