# Generated by Django 5.2.5 on 2025-08-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0009_report_reportattachment_reportcomment_reporthistory_and_more'),
    ]

    operations = [
    ]
