# Generated by Django 5.2.5 on 2025-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0010_auto_20250821_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students2',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='الإيميل'),
        ),
    ]
