# Generated by Django 5.2.5 on 2025-08-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=9)),
                ('img', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('catogry', models.CharField(blank=True, choices=[('الهواتف', 'الهواتف'), ('الإكسسوارات', 'الإكسسوارات'), ('الحواسيب', 'الحواسيب')], null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('prodects', models.ManyToManyField(null=True, to='product.product')),
            ],
        ),
    ]
